"""Add phone_number, date_of_birth and role fields to users

Revision ID: 05f8ae515a0e
Revises: 7332f5e0bc6e
Create Date: 2025-07-06 00:07:28.472491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05f8ae515a0e'
down_revision: Union[str, Sequence[str], None] = '7332f5e0bc6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_column('users', 'date_of_birth')
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
